### ISSUE TITLE
[S1-PB1] Membuat fitur registrasi user dan mitra

### ISSUE THREAD

**Issue by yanharr** [SI-RPL-2022/SI4302_B_TELUSURTASIK#1]
Membuat fitur registrasi user termasuk login

**Comment by RahmaKarina** [comment]
Mockup fitur login mitra
![Login (1)](https://user-images.githubusercontent.com/92136153/160398807-d1801b6f-9a23-4958-a683-332b8bbed3c8.png)

**Comment by RahmaKarina** [comment]
Mockup fitur registrasi Mitra
![Registrasi](https://user-images.githubusercontent.com/92136153/160398924-1d3ee0f7-7af2-4cd8-b28f-02704aff645e.png)

**Comment by RahmaKarina** [comment]
Activity Diagram Registrasi dan Login Mitra
![DA Registrasi Mitra](https://user-images.githubusercontent.com/92136153/160401941-2eb64c50-929d-45f1-8662-edb7c8c9fbf6.jpg)
