### ISSUE TITLE
[S2-PBI3]Membuat fitur wishlist untuk menandakan objek wisata yang ingin dituju

### ISSUE THREAD

**Issue by tasyalaw** [SI-RPL-2022/SI4302_B_TELUSURTASIK#15]
Sebagai User, Saya dapat menambahkan dan menghapus objek wisata sebagai keinginan

**Comment by denayutiara** [comment]
Uploading 2022-05-29 22-47-58.mp4…

**Comment by denayutiara** [comment]
https://user-images.githubusercontent.com/92213568/170879491-d76d6e34-a904-40d3-955d-95f188bf4236.mp4
