### ISSUE TITLE
[S3-PBI2] Membuat Fitur Recently Visit

### ISSUE THREAD

**Issue by tasyalaw** [SI-RPL-2022/SI4302_B_TELUSURTASIK#24]

**Comment by tasyalaw** [comment]
Mockup Recently Visit
![Recently Wishlist](https://user-images.githubusercontent.com/92136153/171775004-21c827ad-c5f4-42ac-9b02-d99fb9410c2a.png)

**Comment by RahmaKarina** [comment]
![Screenshot (47)](https://user-images.githubusercontent.com/92107043/171775189-baed62b9-ce1a-49d3-9fb4-7e00bd487260.png)

**Comment by septiamutiara** [comment]
![recently visit vpd](https://user-images.githubusercontent.com/92212575/171777810-e25f7172-1f7e-4615-9851-92a8c157ca7c.jpg)

**Comment by septiamutiara** [comment]
Activity Diagram Recently Visit
![recently visit vpd](https://user-images.githubusercontent.com/92212575/171777884-44d1600c-90c6-4bdb-87d6-3e1a2d75d705.jpg)

**Comment by yanharr** [comment]
![Recently Wishlist](https://user-images.githubusercontent.com/92177144/171778579-d36bce11-6db3-40c5-ae5b-f9118d5980e1.png)

**Comment by yanharr** [comment]
![Wisata  3 (1)](https://user-images.githubusercontent.com/92177144/171779002-f65c5aea-87ea-4d99-91bc-d94f771ae088.png)

**Comment by tasyalaw** [comment]
Activity Diagram Recently Visit
![recently visit vpd](https://user-images.githubusercontent.com/92212575/171777884-44d1600c-90c6-4bdb-87d6-3e1a2d75d705.jpg)

**Comment by denayutiara** [comment]
<img width="257" alt="recently visit use case diagram" src="https://user-images.githubusercontent.com/92213568/171779254-8833338e-f978-4eb0-8721-80b09173d2f6.PNG">

**Comment by denayutiara** [comment]
https://user-images.githubusercontent.com/92213568/174621349-c6ed2fff-2b7e-4480-b1a7-e295618c9796.mp4

Demo Fitur Recently Visit
