### ISSUE TITLE
[S3-PBI5] Membuat Fitur dashboard Mitra

### ISSUE THREAD

**Issue by tasyalaw** [SI-RPL-2022/SI4302_B_TELUSURTASIK#25]

**Comment by yanharr** [comment]
![Dashboard mitra](https://user-images.githubusercontent.com/92177144/171765114-93757116-6c27-413c-9194-dfce29a3b5e8.png)

**Comment by yanharr** [comment]
![Dashboard (1)](https://user-images.githubusercontent.com/92177144/171768884-4f68528f-4efa-4e4f-b50f-ffca41441121.png)

**Comment by yanharr** [comment]
![Dashboard Mitra (1)](https://user-images.githubusercontent.com/92177144/171768999-24f42c23-6c96-4665-b39d-48bc0c45d94d.png)

**Comment by denayutiara** [comment]
<img width="257" alt="Capture" src="https://user-images.githubusercontent.com/92213568/171769312-4e63f32e-1d51-4595-9a09-e56bf297a8ec.PNG">

**Comment by septiamutiara** [comment]
https://user-images.githubusercontent.com/92212575/174938660-0ba1f247-4e37-4d3f-8dc1-6a7e3ebef3c3.mp4
