### ISSUE TITLE
[S2-PBI2] Membuat fitur wisata untuk melihat tentang objek wisata yang ingin dituju (Kategori,Search)

### ISSUE THREAD

**Issue by yanharr** [SI-RPL-2022/SI4302_B_TELUSURTASIK#4]
Membuat fitur wisata untuk melihat tentang objek wisata yang ingin dituju

**Comment by ekkynovrizalam** [comment]
harus bisa filter dan search

**Comment by yanharr** [comment]
https://user-images.githubusercontent.com/92177144/163922014-a232ffa0-fab3-4c53-93e6-73d46af36b7b.mp4

Karena wisata dengan kategori danau dan taman sudah dihapus pada sesi demo sprint review, maka pada kategori danau dan Taman tidak terdapat objek wisatanya.

**Comment by septiamutiara** [comment]
[PBI2 Membuat fitur wisata untuk melihat tentang objek wisata yang ingin dituju (kategori, search).zip](https://github.com/SI-RPL-2022/SI4302_B_TELUSURTASIK/files/8794904/PBI2.Membuat.fitur.wisata.untuk.melihat.tentang.objek.wisata.yang.ingin.dituju.kategori.search.zip)

**Comment by septiamutiara** [comment]
https://user-images.githubusercontent.com/92212575/170905142-a3b8158e-ee47-497e-8500-fee93d5a9c8a.mp4
