### ISSUE TITLE
[S2-PBI4] Membuat fitur FAQ (Admin,User dan Mitra)

### ISSUE THREAD

**Issue by denayutiara** [SI-RPL-2022/SI4302_B_TELUSURTASIK#8]
Membuat fitur Help untuk mencari atau menanyakan kendala maupun menanyakan pertanyaan lainnya

**Comment by ekkynovrizalam** [comment]
1. ditambahkan fitur CRUD untuk FAQ
2. pada form CRUD FAQ disediakan kategori publik atau mitra
3. ditambahkan tombol chat to whatsapp

**Comment by tasyalaw** [comment]
Demo fitur FAQ/Help
https://user-images.githubusercontent.com/92136153/170611667-b2b71f5c-05d9-45cd-bf2b-81489a857ec7.mp4

**Comment by tasyalaw** [comment]
Demo fitur FAQ/Help
https://user-images.githubusercontent.com/92136153/170628596-b48bb8af-2b40-46a5-bc55-a313106f49fc.mp4

**Comment by ekkynovrizalam** [comment]
@tasyalaw video tidak bisa diputar. tolong upload lagi ya

**Comment by tasyalaw** [comment]
https://user-images.githubusercontent.com/92136153/171757826-f532b91f-0a52-486c-aeb0-b40dbd0d5dcd.mp4



> @tasyalaw video tidak bisa diputar. tolong upload lagi ya
