### ISSUE TITLE
[S2-PBI1] Membuat fitur ulasan untuk meyakinkan customer berkunjung ke objek wisata tersebut

### ISSUE THREAD

**Issue by yanharr** [SI-RPL-2022/SI4302_B_TELUSURTASIK#9]
Membuat fitur ulasan untuk meyakinkan konsumen berkunjung ke objek wisata tersebut

**Comment by RahmaKarina** [comment]
https://user-images.githubusercontent.com/92107043/170665140-7ff7558a-ad2c-493c-abc2-97887a5e41f9.mp4
